imageRepository: logicmonitor/argus
imageTag: v4
imagePullPolicy: Always
disableAlerting: false
deleteDevices: true
debug: false
enableRBAC: "enableRBAC"
clusterName: <<clusterName>>
accessID: <<accessID>>
accessKey: <<accessKey>>
account: <<account>>
etcdDiscoveryToken: <<etcdDiscoveryToken>>
proxyUser: ""
proxyPass: ""
proxyURL: ""
clusterGroupID: <<clusterGroupID>>
nodeSelector: {}
affinity: {}
priorityClassName: ""
tolerations: []
filters:
  pod: ""
  service: ""
  node: ""
  deployment: ""
collector:
  imageRepository: logicmonitor/collector
  imageTag: latest
  imagePullPolicy: Always
  secretName: collector
  replicas: <<collector.replicas>>
  size: <<collector.size>>
  groupID: 0
  escalationChainID: 0
  collectorVersion: 0
  useEA: false
  proxyURL: ""
  proxyUser: ""
  proxyPass: ""
  priorityClassName: ""
  tolerations: []
